drop table if exists 财务分析综合表;
create table if not exists 财务分析综合表 (
    报告时间 DATE NOT NULL,
    公司代码 INTEGER NOT NULL,
    报告类型 CHAR(20) NOT NULL,
    公司简称 CHAR(10),
    公司名称 CHAR(50),
    公司地址 CHAR(10),
    行业分类 CHAR(10),
    在职员工的数量合计 NUMERIC,
    支付给职工及为职工支付的现金 NUMERIC,
    [应付职工薪酬（期末余额）] NUMERIC,
    [应付职工薪酬（期初余额）] NUMERIC,
    [员工平均工资（万）] NUMERIC,
    员工工资占营业收入比率 NUMERIC,
    营业收入 NUMERIC,
    归属于上市公司股东的净利润 NUMERIC,
    归属于上市公司股东的扣除非经常性损益的净利润 NUMERIC,
    经营活动产生的现金流量净额 NUMERIC,
    归属于上市公司股东的净资产 NUMERIC,
    总资产 NUMERIC,
    净资产比率 NUMERIC,
    总资产利润率 NUMERIC,
    现金分红金额（含税） NUMERIC,
    现金分红金额占合并报表中归属于上市公司普通股股东的净利润的比率 NUMERIC,
    --营业收入（上期） NUMERIC,
    --归属于上市公司股东的净利润（上期） NUMERIC,
    --归属于上市公司股东的扣除非经常性损益的净利润（上期） NUMERIC,
    --经营活动产生的现金流量净额（上期） NUMERIC,
    归属于上市公司股东的净资产（上期） NUMERIC,
    总资产（上期） NUMERIC,
    人均营业额（万） NUMERIC,
    人均净利润（万） NUMERIC,
    经营活动产生的现金流量净额占净利润的比率 NUMERIC,
    营业收入增长率 NUMERIC,
    归属于上市公司股东的净利润增长率 NUMERIC,
    归属于上市公司股东的扣除非经常性损益的净利润增长率 NUMERIC,
    经营活动产生的现金流量净额增长率 NUMERIC,
    营业成本 NUMERIC,
    投资收益 NUMERIC,
    营业利润 NUMERIC,
    利润总额 NUMERIC,
    所得税费用 NUMERIC,
    净利润 NUMERIC,
    毛利润 NUMERIC,
    销售费用 NUMERIC,
    管理费用 NUMERIC,
    财务费用 NUMERIC,
    研发费用 NUMERIC,
    资本化研发投入 NUMERIC,
    三费总额（销售管理财务） NUMERIC,
    资产减值准备 NUMERIC,
    折旧和摊销费用 NUMERIC,
    所得税费用占剔除投资收益后利润的比率 NUMERIC,
    三费总额占营业收入的比率 NUMERIC,
    费用总额占营业收入的比率 NUMERIC,
    资产减值和折旧摊销占营业收入的比率 NUMERIC,
    营业利润率 NUMERIC,
    毛利率 NUMERIC,
    净利率 NUMERIC,
    平均净资产收益率 NUMERIC,
    营业收入占平均总资产的比率 NUMERIC,
    净资产增长率 NUMERIC,
    研发投入占营业收入的比率 NUMERIC,
    资本化研发投入的比率 NUMERIC,
    --"无形资产-内部研发","所得税税率",
    总股本 NUMERIC,
    每股净利润 NUMERIC,
    每股净资产 NUMERIC,
    固定资产 NUMERIC,
    在建工程 NUMERIC,
    在建工程占固定资产的比率 NUMERIC,
    土地使用权 NUMERIC,
    投资性房地产 NUMERIC,
    商誉 NUMERIC,
    生产资本 NUMERIC,
    利润总额占生产资本的比率 NUMERIC,
    商誉占营业收入的比率 NUMERIC,
    预收款项 NUMERIC,
    应付票据及应付账款 NUMERIC,
    应付账款 NUMERIC,
    预付款项 NUMERIC,
    应收账款 NUMERIC,
    应收票据 NUMERIC,
    --应收票据（上期）NUMERIC,
    应收账款占营业收入的比率 NUMERIC,
    预收总额和应收总额的比率 NUMERIC,
    预收款项和应收账款的比率 NUMERIC,
    流动资产合计 NUMERIC,
    负债合计 NUMERIC,
    流动负债合计 NUMERIC,
    存货 NUMERIC,
    货币资金 NUMERIC,
    短期借款 NUMERIC,
    一年内到期的非流动负债 NUMERIC,--"有息债券(短期借款＋一年内到期的非流动负)","应收票据增加额（本期应收票据余额-上期应收票据余额）",
    短期借债总额 NUMERIC,
    长期借款 NUMERIC,
    应付债券 NUMERIC,
    流动比率 NUMERIC,
    速动比率 NUMERIC,
    现金及现金等价物余额占短期借债的比率 NUMERIC,
    流动资产占总负债的比率 NUMERIC,
    销售商品、提供劳务收到的现金 NUMERIC,
    现金及现金等价物余额 NUMERIC,
    现金及现金等价物净增加额 NUMERIC,
    现金收入和营业收入的比率 NUMERIC,
    应收账款周转率 NUMERIC,
    存货周转率 NUMERIC,
    营业利润占营业资金的比率 NUMERIC,
    营业收入占营业资金的比率 NUMERIC,
    还原后的净资产收益率（ROCE） NUMERIC
);

insert into 财务分析综合表
select
    a.报告时间,
    a.公司代码,
    a.报告类型,
    a.公司简称,
    a.公司名称,
    a.公司地址,
    a.行业分类,
    a.在职员工的数量合计,
    a.支付给职工及为职工支付的现金,
    a.应付职工薪酬（期末余额）,
    a.应付职工薪酬（期初余额）,
    round(replace(a.营业收入,',','')/replace(a.在职员工的数量合计,',','')/10000,0) as [员工平均工资（万）],
    round((replace(a.支付给职工及为职工支付的现金,',','') + replace(a.应付职工薪酬（期末余额）,',','') - replace(a.应付职工薪酬（期初余额）,',',''))/replace(a.营业收入,',',''),4)
        as 员工工资占营业收入比率,
    a.营业收入,
    a.归属于上市公司股东的净利润,
    a.归属于上市公司股东的扣除非经常性损益的净利润,
    a.经营活动产生的现金流量净额,
    a.归属于上市公司股东的净资产,
    a.总资产,
    round(replace(a.经营活动产生的现金流量净额,',','')/replace(a.归属于上市公司股东的净资产,',',''),4) as 净资产比率,
    round(replace(a.归属于上市公司股东的净利润,',','')/replace(a.总资产,',',''),4) as 资本利润率,
    a.[现金分红金额（含税）],
    a.现金分红金额占合并报表中归属于上市公司普通股股东的净利润的比率,
    a.归属于上市公司股东的净资产（上期）,
    a.总资产（上期）,
    round(replace(a.营业收入,',','')/replace(a.在职员工的数量合计,',','')/10000,4) as [人均营业额（万）],
    round(replace(a.归属于上市公司股东的净利润,',','')/replace(a.在职员工的数量合计,',','')/10000,4) as [人均净利润（万）],
    round(replace(a.经营活动产生的现金流量净额,',','')/replace(a.归属于上市公司股东的净利润,',',''),4) as 经营活动产生的现金流量净额占净利润的比率,
    round((replace(a.营业收入,',','') - replace(a.营业收入（上期）,',',''))/replace(a.营业收入（上期）,',',''),4) as 营业收入增长率,
    round((replace(a.归属于上市公司股东的净利润,',','') - replace(a.归属于上市公司股东的净利润（上期）,',',''))/replace(a.归属于上市公司股东的净利润（上期）,',',''),4)
        as 归属于上市公司股东的净利润增长率,
    round((replace(a.归属于上市公司股东的扣除非经常性损益的净利润,',','') - replace(a.归属于上市公司股东的扣除非经常性损益的净利润（上期）,',',''))/replace(a.归属于上市公司股东的扣除非经常性损益的净利润（上期）,',',''),4)
        as 归属于上市公司股东的扣除非经常性损益的净利润增长率,
    round((replace(a.经营活动产生的现金流量净额,',','') - replace(a.经营活动产生的现金流量净额（上期）,',',''))/replace(a.经营活动产生的现金流量净额（上期）,',',''),4)
        as 经营活动产生的现金流量净额增长率,
    a.营业成本,
    a.投资收益,
    a.三、营业利润 as 营业利润,
    a.四、利润总额 as 利润总额,
    a.所得税费用,
    a.五、净利润 as 净利润,
    replace(a.营业收入,',','') - replace(a.营业成本,',','') as 毛利润,
    a.销售费用,
    a.管理费用,
    a.财务费用,
    a.研发费用,
    a.资本化研发投入,
    replace(a.销售费用,',','') + replace(a.管理费用,',','') + replace(a.财务费用,',','') as 三费总额（销售管理财务）,
    a.资产减值准备,
    replace(a.固定资产折旧、油气资产折耗、生产性生物资产折旧,',','') + replace(a.无形资产摊销,',','') + replace(a.长期待摊费用摊销,',','')
        as 折旧和摊销费用,
    round(replace(a.所得税费用,',','')/(replace(a.四、利润总额,',','') - replace(a.投资收益,',','')),4) as 所得税费用占剔除投资收益后利润的比率,
    --"无形资产-内部研发","资产减值准备","折旧和摊销","所得税税率",
    round((replace(a.销售费用,',','') + replace(a.管理费用,',','') + replace(a.财务费用,',',''))/replace(a.营业收入,',',''),4)
        as 三费总额占营业收入的比率,
    round((replace(a.销售费用,',','') + replace(a.管理费用,',','') + replace(a.财务费用,',','') + replace(a.研发费用,',',''))/replace(a.营业收入,',',''),4)
        as 费用总额占营业收入的比率,
    round((replace(a.资产减值准备,',','') + replace(a.固定资产折旧、油气资产折耗、生产性生物资产折旧,',','') + replace(a.无形资产摊销,',','') + replace(a.长期待摊费用摊销,',',''))/replace(a.营业收入,',',''),4)
        as 资产减值和折旧摊销占营业收入的比率,
    round(replace(a.三、营业利润,',','')/replace(a.营业收入,',',''),4) as 营业利润率,
    round((replace(a.营业收入,',','') - replace(a.营业成本,',',''))/replace(a.营业收入,',',''),4) as 毛利率,
    round(replace(a.五、净利润,',','')/replace(a.营业收入,',',''),4) as 净利率,
    round(replace(a.五、净利润,',','')*2/(replace(a.归属于上市公司股东的净资产,',','') + replace(a.归属于上市公司股东的净资产（上期）,',','')),4) as 平均净资产收益率,
    round(replace(a.营业收入,',','')*2/(replace(a.总资产,',','') + replace(a.总资产（上期）,',','')),4) as 营业收入占平均总资产的比率,
    round((replace(a.归属于上市公司股东的净资产,',','') - replace(a.归属于上市公司股东的净资产（上期）,',',''))/replace(a.归属于上市公司股东的净资产（上期）,',',''),4)
        as 净资产增长率,
    round((replace(a.资本化研发投入,',','') + replace(a.研发费用,',',''))/replace(a.营业收入,',',''),4) as 研发投入占营业收入的比率,
    round(replace(a.资本化研发投入,',','')/(replace(a.资本化研发投入,',','') + replace(a.研发费用,',','')),4) as 资本化研发投入的比率,
    a.期末总股本 as 总股本,
    round(replace(a.归属于上市公司股东的净利润,',','')/replace(a.期末总股本,',',''),2) as 每股净利润,
    round(replace(a.归属于上市公司股东的净资产,',','')/replace(a.期末总股本,',',''),2) as 每股净资产,
    a.固定资产,
    a.在建工程,
    round(replace(a.在建工程,',','')/replace(a.固定资产,',',''),4) as 在建工程占固定资产的比率,
    a.土地使用权,
    a.投资性房地产,
    a.商誉,
    replace(a.固定资产,',','') + replace(a.在建工程,',','') + replace(a.土地使用权,',','') + replace(a.投资性房地产,',','') as 生产资本,
    round(replace(a.四、利润总额,',','')/(replace(a.固定资产,',','') + replace(a.在建工程,',','') + replace(a.土地使用权,',','') + replace(a.投资性房地产,',','')),4)
        as 利润总额占生产资本的比率,
    round(replace(a.商誉,',','')/replace(a.营业收入,',',''),4) as 商誉占营业收入的比率,
    a.预收款项,
    a.应付票据及应付账款,
    a.应付账款,
    a.预付款项,
    a.应收账款,
    a.应收票据,
    round(replace(a.应收账款,',','')/replace(a.营业收入,',',''),2) as 应收账款占营业收入的比率,
    round((replace(a.预收款项,',','') + replace(a.应付票据及应付账款,',',''))/(replace(a.预付款项,',','') + replace(a.应收账款,',','') + replace(a.应收票据,',','')),2)
        as 预收总额和应收总额的比率,
    round(replace(a.预收款项,',','')/replace(a.应收账款,',',''),2) as 预收款项和应收账款的比率,
    a.流动资产合计,
    a.负债合计,
    a.流动负债合计,
    a.存货,
    a.货币资金,
    a.短期借款,
    a.一年内到期的非流动负债,--"有息债券(短期借款＋一年内到期的非流动负)","应收票据增加额（本期应收票据余额-上期应收票据余额）",
    replace(a.短期借款,',','') + replace(a.一年内到期的非流动负债,',','') as 短期借债总额,
    a.长期借款,
    a.应付债券,
    round(replace(a.流动资产合计,',','')/replace(a.流动负债合计,',',''),2) as 流动比率,
    round((replace(a.流动资产合计,',','') - replace(a.存货,',',''))/replace(a.流动负债合计,',',''),2) as 速动比率,
    round(replace(a.六、期末现金及现金等价物余额,',','')/(replace(a.短期借款,',','') + replace(a.一年内到期的非流动负债,',','')),4)
        as 现金及现金等价物余额占短期借债的比率,
    round(replace(a.流动资产合计,',','')/replace(a.负债合计,',',''),4) as 流动资产占总负债的比率,
    a.销售商品、提供劳务收到的现金,
    a.[六、期末现金及现金等价物余额] as 现金及现金等价物余额,
    a.五、现金及现金等价物净增加额 as 现金及现金等价物净增加额,
    round(replace(a.六、期末现金及现金等价物余额,',','')/replace(a.营业收入,',',''),2) 现金收入和营业收入的比率,
    round(replace(a.营业收入,',','')/replace(a.应收账款,',',''),2) as 应收账款周转率,
    round(replace(a.营业收入,',','')/replace(a.存货,',',''),2) as 存货周转率,
    round(replace(a.三、营业利润,',','')/(replace(a.流动资产合计,',','') - replace(a.流动负债合计,',','')),2) as 营业利润占营业资金的比率,
    round(replace(a.营业收入,',','')/(replace(a.流动资产合计,',','') - replace(a.流动负债合计,',','')),2) as 营业收入占营业资金的比率,
    round(replace(a.归属于上市公司股东的净利润,',','')/replace(a.归属于上市公司股东的净资产（上期）,',',''),2) 还原后的净资产收益率（ROCE）
from 财务分析基础表 a;

CREATE INDEX IF NOT EXISTS [财务分析综合表索引] on [财务分析综合表] (
    报告时间,
    公司代码,
    报告类型
);

select * from 财务分析综合表;